version: "3.9"

services:
  perfumeservice:
    image: perfumeservice
    container_name: perfumeservice
    build:
      context: .
      dockerfile: PerfumeService/Dockerfile
    expose:
      - "8080"
    depends_on:
      - postgresdb
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgresdb;Port=5432;Database=perfumedb;Username=perfumeuser;Password=perfumepass
    networks:
      - perfume-network

  postgresdb:
    image: postgres:16
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: perfumedb
      POSTGRES_USER: perfumeuser
      POSTGRES_PASSWORD: perfumepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - perfume-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgresdb
    networks:
      - perfume-network

volumes:
  postgres_data:

networks:
  perfume-network:
    driver: bridge
