# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  perfumeservice:
    build:
      context: "C:\\Users\\Artur\\RiderProjects\\PerfumeService"
      dockerfile: "PerfumeService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/PerfumeService.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net10.0/PerfumeService.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "perfumeservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\Artur\\RiderProjects\\PerfumeService\\PerfumeService:/app:rw"
    - "C:\\Users\\Artur\\RiderProjects\\PerfumeService:/src:rw"
    - "C:\\Users\\Artur\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
