# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  perfumeservice:
    build:
      context: "C:\\Users\\Artur\\RiderProjects\\PerfumeService"
      dockerfile: "PerfumeService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net10.0/PerfumeService.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "perfumeservice:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "C:\\Users\\Artur\\RiderProjects\\PerfumeService\\PerfumeService:/app:rw"
    - "C:\\Users\\Artur\\RiderProjects\\PerfumeService:/src:rw"
    - "C:\\Users\\Artur\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Artur\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.3.1\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.3.1\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Artur\\AppData\\Local\\JetBrains\\Rider2025.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2026_1_18_18_47_06:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
